apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracksapi-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: tracksapi-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tracksapi
                port:
                  number: 8080