resources:
  - ../../base
patches:
  - path: patch-persistentvolumeclaim.yaml
    target:
      kind: PersistentVolumeClaim
      name: smb-tracksapi-pvc
  - path: patch-acr-externalsecret.yaml
    target:
      kind: ExternalSecret
      name: acr-externalsecret
  - path: patch-etl-externalsecret.yaml
    target:
      kind: ExternalSecret
      name: etl-external-secret      
  - path: patch-etl-configmap.yaml
    target:
      kind: ConfigMap
      name: etl-config         
  - path: patch-cluster.yaml
    target:
      kind: Cluster
      name: cluster.yaml
