resources:
  - ../../base
patches:
  - path: patch-persistentvolumeclaim.yaml
    target:
      kind: PersistentVolumeClaim
      name: smb-tracksapi-pvc
  - path: patch-acr-externalsecret.yaml
    target:
      kind: ExternalSecret
      name: acr-externalsecret
