apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracksapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracksapi
  template:
    metadata:
      labels:
        app: tracksapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: tracksapi
        image: crrvmaindev.azurecr.io/tracksapi:1.0.3
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
            name: tracksapi-configmap
          - secretRef:
            name: postgres-app        
