apiVersion: v1
kind: ConfigMap
metadata:
  name: tracksapi-config
data:
  ApplyMigrations: "true"
  LogPath: "/var/log/tracksApi"
  Mp3Path: "/mnt/content/Audio_XenoxContent_HqMp3"
  AacPath: "/mnt/content/Audio_XenoxContent_Aac"