apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-moon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-moon
  template:
    metadata:
      labels:
        app: hello-moon
    spec:
      containers:
        - name: hello-moon
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
